### ISSUE TITLE
UpdateRemotePlugins command hangs

### ISSUE THREAD

**Issue by bigfish** [neovim/node-host#1]
Hi, this looks very promising, however after I followed the instructions, I cannot find any evidence that it is working. 

I have installed on Ubuntu using PPA,
NVIM 0.0.0-alpha (compiled Sep 28 2015 21:21:49)
Commit: ?
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -Wvla -std=gnu99 -fstack-protector --param ssp-buffer-size=4 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/build/neovim-CFa3dS/neovim-0.0.0+git201509280033+1917+14~ubuntu14.04.1/build/config -I/build/neovim-CFa3dS/neovim-0.0.0+git201509280033+1917+14~ubuntu14.04.1/src -I/build/neovim-CFa3dS/neovim-0.0.0+git201509280033+1917+14~ubuntu14.04.1/.deps/usr/include -I/build/neovim-CFa3dS/neovim-0.0.0+git201509280033+1917+14~ubuntu14.04.1/.deps/usr/include -I/usr/include/luajit-2.0 -I/build/neovim-CFa3dS/neovim-0.0.0+git201509280033+1917+14~ubuntu14.04.1/.deps/usr/include -I/build/neovim-CFa3dS/neovim-0.0.0+git201509280033+1917+14~ubuntu14.04.1/.deps/usr/include -I/build/neovim-CFa3dS/neovim-0.0.0+git201509280033+1917+14~ubuntu14.04.1/.deps/usr/include -I/build/neovim-CFa3dS/neovim-0.0.0+git201509280033+1917+14~ubuntu14.04.1/.deps/usr/include -I/usr/include -I/build/neovim-CFa3dS/neovim-0.0.0+git201509280033+1917+14~ubuntu14.04.1/build/src/nvim/auto -I/build/neovim-CFa3dS/neovim-0.0.0+git201509280033+1917+14~ubuntu14.04.1/build/include
Compiled by buildd@lgw01-50

I initally used Vundle to clone the node-host repo, then placed the example as example.js in .nvim/rplugin/node/example.js

When I executed the UpdateRemotePlugins command, nvim just hangs.

Any ideas why that happens? I did see an error in .nvimlog, but it may just be because I killed the terminal.. stock Gnome Terminal 3.6.2, btw.

2015/09/29 21:26:29 [info @ main_loop:559] 3047 - Starting Neovim main loop.
2015/09/29 21:26:53 [info @ main_loop:559] 3130 - Starting Neovim main loop.
2015/09/29 21:27:17 [info @ main_loop:559] 3183 - Starting Neovim main loop.
2015/09/29 21:28:15 [error @ call_set_error:743] 3183 - msgpack-rpc: Channel was closed by the client
2015/09/29 21:29:07 [info @ main_loop:559] 3310 - Starting Neovim main loop.
2015/09/29 21:30:20 [info @ main_loop:559] 3474 - Starting Neovim main loop.
2015/09/29 21:30:56 [error @ call_set_error:743] 3474 - msgpack-rpc: Channel was closed by the client
2015/09/29 21:32:16 [info @ main_loop:559] 3712 - Starting Neovim main loop.

**Comment by nhynes** [comment]
@bigfish the problem is that this package depends on an updated version of the client that hasn't yet been published to NPM; sorry for the trouble. This should be addressed soon enough, but if you don't want to wait, in `package.json` change

``` diff
-    "neovim-client": "^1.0.4",
+   "neovim-client": "neovim/node-client",
```

and then `npm install`.

@tarruda would you mind publishing node-client 1.0.5?

**Comment by tarruda** [comment]
@nhynes published

Can I add you as a owner of the package? What is your npm username?

**Comment by nhynes** [comment]
@tarruda Fantastic, thanks a lot. I'd be happy to help maintain the npm package--my username is "nhynes."

**Comment by tarruda** [comment]
Ok, added you as owner

**Comment by bigfish** [comment]
It works now, thanks for the quick fix, @nhynes !
