### ISSUE TITLE
CSS Beautify Example Not Working

### ISSUE THREAD

**Issue by kakposoe** [neovim/node-host#11]
I've followed all instructions and have got to the point where plugins are registering which is great. 

However I haven't been able to get the CSS Beautify example working. 

I inserted the following into the node-host/package.json to be on the safe side but it didn't solve the issue:

`"neovim-client": "neovim/node-client"`

To be more specific, once I type :BeautifyCSS into the neovim command line, the cursor goes over ":" and freezes.

Anything I'm missing out? Thank you for your time!

**Comment by nhynes** [comment]
Thanks for pointing this out! I won't be able to do any serious debugging until Thursday, but I'll take a look then and post back with a solution.

**Comment by nhynes** [comment]
Okay, it should be working now. Thanks again for catching the error!

**Comment by kakposoe** [comment]
Working perfectly. Thank you very much.
