### ISSUE TITLE
Post-Install hook

### ISSUE THREAD

**Issue by Superpat** [neovim/node-host#12]
From the readme todo list: Plugin manager that allows post-install hooks for npm install

This is already possible with [vim-plug](https://github.com/junegunn/vim-plug), it works with both vim and neovim and has support for nvim's asynchronous handles. You simple add `Plug 'neovim/node-host' {'do' : 'npm install'}` to the  init.vim.

**Comment by nhynes** [comment]
Pretty neat, thanks for the tip! I think that the TODO was something more along the lines of waiting for Neovim to get an official package manager, but I'll add this in a blurb about installation methods as soon as I finish testing this and others out.

**Comment by Superpat** [comment]
Hmm thought that email response was inlined into the comments.. But for the sake of others; Is the neovim project planning an official plugin manager? Vim-Plug is in the related projects page and I always thought that was the one they suggested. It also works great, I used to use vundle but I've been using vim-plug for a year now and I dont think I'll ever look back.

**Comment by justinmk** [comment]
> Is the neovim project planning an official plugin manager?

There's an open ticket but it's low priority.
