### ISSUE TITLE
Track msgpack fix for array of empty string  mcollina/msgpack5/issues/48

### ISSUE THREAD

**Issue by snoe** [neovim/node-host#18]
One of my users uncovered and fixed a bug  in the underlying msgpack lib. Which has since been released under msgpack 3.4.1 

I'm raising an issue here as a sort of master tracking issue, hoping we can coordinate with @tarruda and @nhynes to get the versions bumped in https://github.com/tarruda/node-msgpack5rpc and https://github.com/neovim/node-client and finally here.

https://github.com/mcollina/msgpack5/issues/48
https://github.com/snoe/clj-refactor.nvim/issues/8

**Comment by nhynes** [comment]
Seems reasonable. You might get a more prompt response if you make a PR/issue in [node-msgpack5rpc](https://github.com/tarruda/node-msgpack5rpc) [and then reference the contrib here so that it gets updated automatically].

**Comment by snoe** [comment]
Looking at this again this morning, it looks like updating node-host to use neovim-client 2.1.0 actually does bring in the msgpack 3.4 patch. So https://github.com/neovim/node-host/issues/17 should fix this as well.
