### ISSUE TITLE
Multiple plugin issues

### ISSUE THREAD

**Issue by mhartington** [neovim/node-host#22]
Seems that #21 is back. Trying to load more than one node/JS based plugin leads to 

```
function remote#host#UpdateRemotePlugins[6]..<SNR>26_RegistrationCommands, line 20
Vim(let):ch 6 was closed by the client
```

When trying to run `UpdateRemotePlugins`.
Happy to try and help out, where should I start looking?

**Comment by justinmk** [comment]
Nothing changed on the node side, so maybe not the same issue. First thing to do is see why the client is closing itself (or crashing?)

I'm not familiar with nodejs debugging, but in general, find the place where the client shuts down, e.g.:

https://github.com/neovim/node-client/blob/master/index.js#L189

then set a breakpoint on it, repro the issue and save the stacktrace.

**Comment by mhartington** [comment]
Generating a debug build of nvim and reading `.nvimlog` only prints this

```
2017/05/21 21:06:36 INFO  58556/main:547: starting main loop
2017/05/21 21:06:38 ERROR 58556/call_set_error:733: RPC: ch 2 was closed by the client
```

It also seems that my typical methods of debugging are hitting a wall. 
I can start to attach a debugger, but I'm guessing that because it's running from inside nvim, it chokes up. Trying a few more things later tonight, but so far I cannot find anything more

**Comment by justinmk** [comment]
nvim isn't going to have any insight about why the client closed, the error indicates that the client initiated the disconnection. What I was suggesting above is to connect to the _client_ or "host" (node.js process(es)) and use a javascript debugger (whatever that is, chrome devtools i assume) :)

**Comment by ricardogcolombo** [comment]
I have the same problem here.
`
function remote#host#UpdateRemotePlugins[6]..<SNR>69_RegistrationCommands, line 20
Vim(let):ch 1 was closed by the client
`


Steps to reproduce
Copy the example plugin into rplugin/node (demo_beautify_css.js) 

Create a new one (only with the name+'.js') in the folder. (I'm not able to make it work without the .js name)
Then try to run UpdateRemotePlugins

**Comment by billyvg** [comment]
This is now fixed with the new `node-client`
