### ISSUE TITLE
Change remote#Host#register in order to get any plugin name

### ISSUE THREAD

**Issue by ricardogcolombo** [neovim/node-host#23]
Change
`call remote#host#Register('node', '*.js', function('js_host#RequireJSHost'))`
to
`call remote#host#Register('node', '*', function('js_host#RequireJSHost'))`

In order to get any plugin folder insde /rplugin/node  and not only names with .js (e.g demo_beautify_css.js -> demo_beautify_css/)

**Comment by nhynes** [comment]
This was done intentionally to make the `require` consistent for both plugin files and directories. . Is there a particular issue that you're having that isn't solved by naming the plugin directory `foo.js`?

**Comment by ricardogcolombo** [comment]
Ok, Do you mean javascript `require`? In that case you don't need to use ".js".

In summary I don't have any issue and should be solved renaming the directory, so I'm closing this issue.

**Comment by billyvg** [comment]
This has, embarrassingly, caused me some lost time (more than I care to admit). I think it's much more intuitive to not have a `*.js` search pattern (especially for directories).
