### ISSUE TITLE
Errors thrown in plugins hard to debug

### ISSUE THREAD

**Issue by dlants** [neovim/node-host#26]
uncaught errors in plugins seem to be getting sent to `stdout`, which makes nvim close the channel (see https://github.com/neovim/neovim/issues/4468#issuecomment-279239200 )

These errors are quite hard to find, and result in further plugin requests to show an unhelpful `Invalid channel "3"` message.

I think it's due to this https://github.com/neovim/node-host/blob/6ad15da01e9eb7e2975dff8f26836b9d1529b7b1/lib/plugin.js#L137

I'm not sure if there's something better to do with stderr, but it would be great to send uncaught exceptions somewhere where they can be more obvious.

**Comment by billyvg** [comment]
Yep! Can I ask what plugin you are using, or are you writing a plugin? We are currently rewriting node-host and node-client. The new client will provide much better logging/debugging options.

**Comment by dlants** [comment]
I'm writing my own.

Any idea about when the new client will land? Will the API be similar?

**Comment by billyvg** [comment]
@dlants API will be very similar, biggest difference is it will be a Promise-only API.

**Comment by justinmk** [comment]
Please re-open at https://github.com/neovim/node-client if necessary.

https://github.com/neovim/node-host repro is deprecated.

**Comment by Delapouite** [comment]
@justinmk you may want to use this new GitHub feature to indicate clearly that repo is deprecated : https://github.com/blog/2460-archiving-repositories
