### ISSUE TITLE
Example plugin structure

### ISSUE THREAD

**Issue by watsoncj** [neovim/node-host#32]
Very excited to find this project!

Not being familiar with the `rplugin` folder convention, an example plugin would be extremely useful.

Ideally the example would also include how to install the plugin (local or remote) using one of the popular package managers.

~Additionally the example snippet on node-client seems to be using language features that are not directly supported in node (ES2015 modules) . Is there a preprocessing step required?~

It might also be useful to point out that the example snippet in the node-client readme is in TypeScript.

**Comment by justinmk** [comment]
~~Example would be good, I think it should be in the README though, not an actual file (which is more likey to get stale/forgotten). It should be something like:~~

see https://github.com/neovim/node-client#writing-a-plugin

**Comment by justinmk** [comment]
Oops, I got confused, as probably others do.

This repo is deprecated. 

See https://github.com/neovim/node-client#writing-a-plugin instead.

@billyvg think we can delete https://github.com/neovim/node-host now ?
