### ISSUE TITLE
How to interact with the async client-api while returning a value from a sync handler?

### ISSUE THREAD

**Issue by snoe** [neovim/node-host#5]
Hi, I think this might be a deficiency in the API, but I would love to hear otherwise.

Because all of the neovim-client functions are asynchronous I cannot figure out how to do work on the result of one of those functions and return the result of that work through a *Sync handler.

I've spent a number of hours trying to leverage ES6 generators/yield, clojurescript core.async and fabric but I think they all require you to give up control of the main execution context which causes the client callback to return.

Is this (toy example) possible?

``` js
plugin.functionSync("CurrentLineLength", {}, function(nvim) {
   // return nvim.getCurrentLine(function(err, line) {return line.length}) // returns null
   // return nvim.getCurrentLine().length // I would like to do this
  return null;
})
```

I'm asking because I ran into a wall trying to fix this issue properly https://github.com/snoe/nvim-parinfer.js/issues/6 It's also very possible that I'm thinking about transforming the buffer in the wrong way that's making me wish for a synchronous approach.

**Comment by nhynes** [comment]
I'm very sorry for the lengthy delay! I get what you're going for here; given the rarity of synchronous node code, it'd be great if the `*Sync` functions were synchronous w.r.t. node rather than just neovim. I'll work on implementing this now!

**Comment by nhynes** [comment]
Please let me know if that solves your problem!

**Comment by snoe** [comment]
That's great! Thanks @nhynes!
