### ISSUE TITLE
Returning an array of strings from a functionSync produces zeroes in nvim

### ISSUE THREAD

**Issue by snoe** [neovim/node-host#6]
When I return an array with empty strings (particularly at the start of the array), subsequent elements are replaced with zeroes

``` js
plugin.functionSync('TestArray', function(nvim) {
  return [""," "]
})
```

in nvim `:echo TestArray()` produces: `['', 0]` but I'd expect `["", " "]`

I tried to reproduce this by passing the same array with `node-client` calls but was unable to (although this test could be flawed):

``` js
var cp = require('child_process');
var attach = require('neovim-client');

var nvim_proc = cp.spawn('nvim', ['-u', 'NONE', '-N', '--embed'], {});
attach(nvim_proc.stdin, nvim_proc.stdout, function(err, nvim) {
  nvim.setVar('testlines', ["", " "],function(err, res) {
    nvim.commandOutput('echo testlines',function(err,res) {
      console.log(res == '\n[\'\', \' \']');
    });
  });
});
```

**Comment by snoe** [comment]
I noticed that using the vim->vim host has the same problem.

``` vim
let vim = rpcstart('nvim', ['--embed'])
echo rpcrequest(vim, 'vim_eval', "['',' ']")
```

produces `['', 0]` as well

**Comment by nhynes** [comment]
Interesting. Have you registered this as an issue in [neovim/neovim](https://github.com/neovim/neovim)?

**Comment by justinmk** [comment]
@snoe Found the same thing and reported it here (thanks): https://github.com/neovim/neovim/issues/3844

So definitely a core nvim bug.
